### ISSUE TITLE
SPI probable bug

### ISSUE THREAD

**Issue by ikalogic** [ikalogic/ScanaStudio-Decoders#4]
https://www.ikalogic.com/answers/spi-decoder-bug/

**Comment by FB-DevSki** [comment]
![image](https://user-images.githubusercontent.com/12776361/32878428-3b2ec7d8-caa6-11e7-8c29-88f5de11ccbe.png)

SPI decoder sometimes works, sometimes does not work. This cannot be controlled.
It happens at startup, every time.
Is this a bug/feature ? Is there a workaround ?  
I use IKA-SPI decoder. Software is in the latest 3.0.5 version. OS is Windows 7 professional.
Device is SQ100.
On the same signal, Sigrok/open logic scanner can decode correctly.
Please respond.

**Comment by BastitNi** [comment]
Hi FB-DevSki,
This is a known issue, we are working on it. The problem is that the signals begin at the middle of a SPI frame, so decoder doesn't able to decode it.
However, you can make it work if you use Signal Overlay to make signal High until the start of the next SPI frame. Of course, it's not the final solution.
![scana_improve_spi](https://user-images.githubusercontent.com/18550167/32881422-7e11ae98-cab1-11e7-90b2-75f42895cd0c.gif)
